name: Update README with Recent Activity

on:
  schedule:
    - cron: "23 2 * * *"   # 每日固定時間跑就好，別每小時洗版
  workflow_dispatch:

permissions:
  contents: write          # 需要回寫 README
  # metadata: read         # 通常預設就是 read，不必特別寫

concurrency:
  group: update-readme
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@v0.4.5
        env:
          # 用內建 token，避免 fine-grained PAT 打不到 user 端點
          GITHUB_TOKEN: ${{ github.token }}
        with:
          GH_USERNAME: jacky789789
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          TARGET_FILE: README.md
          MAX_LINES: 10
          COMMIT_MSG: "chore(readme): update GitHub activity [skip ci]"
          # 建議先關掉 keep-alive 空提交，避免污染歷史
          # EMPTY_COMMIT_MSG: ":memo: keep workflow alive"
