name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 * * * *"   # 每小時執行一次
  workflow_dispatch:       # 可以手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允許寫入 README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 必須用 env
        with:
          COMMIT_MSG: "chore: update GitHub activity"
          MAX_LINES: 10
