name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 * * * *"   # 每小時執行一次（UTC）
  workflow_dispatch:
  # （選配）當你調整這支 workflow 時自動跑一次，方便驗證
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/update-readme.yml"

permissions:
  contents: write   # 僅開必要權限（最小權限）

concurrency:
  group: update-readme
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update GitHub activity [skip ci]"
          MAX_LINES: 10
