name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 * * * *"   # 每小時執行一次
  workflow_dispatch:       # 可以手動觸發
  push:
    branches: [ main ]     # 每次 main 有更新也會觸發

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允許寫入 README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@v0.4.1
        with:
          GH_TOKEN: ${{good }}

