- name: Ensure single marker exists exactly once
  run: |
    set -euo pipefail
    file="README.md"
    marker='<!--START_SECTION:activity-->'

    if [[ ! -f "$file" ]]; then
      echo "::error title=Missing README.md::$file not found"; exit 1
    fi

    # 用 ( ... || true ) 包住 grep，避免沒匹配時因 pipefail 退出
    count=$( (grep -aoF "$marker" "$file" || true) | wc -l )
    echo "Found $count occurrence(s) of $marker"

    if [[ "${count:-0}" -ne 1 ]]; then
      echo "::error title=Marker invalid::Found $count occurrences of $marker (expected 1)"; exit 1
    fi

    echo "Marker OK"
